export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_COURSE_CART = 'REMOVE_COURSE_CART';
export const ADD_PAYMENT = 'ADD_PAYMENT';
export const DELETE_COURSE = 'DELETE_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
export const CREATE_COURSE = 'CREATE_COURSE';